# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "034293756b5b74f6ebc869c310e4de1d"
application_url = "https://tag-puzzle-kids-absolute.trycloudflare.com"
embedded = true
name = "Mattress Dynasity"
handle = "mattress-dynasity"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https-dynastymattress-com.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://tag-puzzle-kids-absolute.trycloudflare.com/auth/callback",
  "https://tag-puzzle-kids-absolute.trycloudflare.com/auth/shopify/callback",
  "https://tag-puzzle-kids-absolute.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
