# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9b353e9ce24bdd2c71d6ea8a90d21ecf"
<<<<<<< HEAD
application_url = "https://sec-sri-flesh-pricing.trycloudflare.com"
=======
application_url = "https://mattress-dynasty-shopify-app-frontend-v39j.vercel.app/"
>>>>>>> f2744d80538b9d1d1f1d7b0a070a1a3f35a26a71
embedded = true
name = "Mattress Dynasity"
handle = "lean-policy-app-3"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https-quickstart-0cb4d6bf.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_customers,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://sec-sri-flesh-pricing.trycloudflare.com/auth/callback",
  "https://sec-sri-flesh-pricing.trycloudflare.com/auth/shopify/callback",
  "https://sec-sri-flesh-pricing.trycloudflare.com/api/auth/callback"
=======
  "https://mattress-dynasty-shopify-app-frontend-v39j.vercel.app/auth/callback",
  "https://mattress-dynasty-shopify-app-frontend-v39j.vercel.app/auth/shopify/callback",
  "https://mattress-dynasty-shopify-app-frontend-v39j.vercel.app/api/auth/callback"
>>>>>>> f2744d80538b9d1d1f1d7b0a070a1a3f35a26a71
]

[pos]
embedded = true

[app_preferences]
url = "https://d1db-2400-adc7-15b-c000-85da-a75b-5c75-dcd7.ngrok-free.app/"
